import type { Point } from '../types';
import type { GameState, Actor } from '../types';

/**
 * The specific type of action the intent represents.
 */
export type IntentType = 'ATTACK' | 'MOVE' | 'WAIT' | 'USE_SKILL';

/**
 * The standardized "Contract" that allows Agency to be swappable.
 * Generated by Layer 1 (Strategy), filtered by Layer 2 (Middleware), executed by Layer 3 (Tactical).
 */
export interface Intent {
    type: IntentType;
    actorId: string;
    skillId: string;
    primaryTargetId?: string; // Unit ID
    targetHex?: Point;        // For ground-targeted skills
    priority: number;
    metadata: {
        expectedValue: number;  // The "Brain's" predicted utility
        reasoningCode: string;  // For headless debugging (e.g., "RETREAT_LOW_HP")
        isGhost: boolean;       // Flag for recorded data
        rngSeed?: number;       // Injected seed for deterministic replays
        rngConsumption?: number; // Number of RNG steps consumed during decision making
    };
}

/**
 * Layer 1: The Strategy Calculator (The "Brain").
 */
export interface IStrategyProvider {
    /**
     * Calculates the best intent for the given actor in the current game state.
     * This method should be pure-ish (no side effects on GameState).
     */
    getIntent(gameState: GameState, actor: Actor): Promise<Intent> | Intent;
}
