import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseSkillAuthoringDefinition } from '../src/data/skill-authoring';
import { buildSkillLibraryMetadata, compileSkillAuthoringDefinition } from '../src/systems/skill-runtime/compile';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const engineRoot = path.resolve(__dirname, '..');
const repoRoot = path.resolve(engineRoot, '..', '..');
const skillsDir = path.join(engineRoot, 'src', 'data', 'skills');
const generatedDir = path.join(engineRoot, 'src', 'generated');
const generatedFile = path.join(generatedDir, 'skill-runtime.generated.ts');
const metadataDir = path.join(repoRoot, 'artifacts', 'skills');
const metadataFile = path.join(metadataDir, 'skill-library.metadata.json');

const renderGeneratedFile = (
    compiledDefinitions: unknown[],
    metadata: unknown
): string => {
    const ids = compiledDefinitions.map((definition: any) => definition.id);
    return `/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by: packages/engine/scripts/generateSkillRuntime.ts
 */
import type { SkillLibraryMetadata, SkillRuntimeDefinition } from '../systems/skill-runtime/types';

export const GENERATED_RUNTIME_SKILLS: SkillRuntimeDefinition[] = ${JSON.stringify(compiledDefinitions, null, 2)};

export const GENERATED_RUNTIME_SKILL_IDS = ${JSON.stringify(ids, null, 2)} as const;

export type GeneratedRuntimeSkillID = typeof GENERATED_RUNTIME_SKILL_IDS[number];

export const GENERATED_RUNTIME_SKILL_LIBRARY_METADATA: SkillLibraryMetadata = ${JSON.stringify(metadata, null, 2)};
`;
};

const main = async () => {
    const entries = await fs.readdir(skillsDir, { withFileTypes: true });
    const fileNames = entries
        .filter(entry => entry.isFile() && entry.name.endsWith('.skill.json'))
        .map(entry => entry.name)
        .sort((left, right) => left.localeCompare(right));

    const compiled = [];
    for (const fileName of fileNames) {
        const absPath = path.join(skillsDir, fileName);
        const raw = await fs.readFile(absPath, 'utf8');
        const authored = parseSkillAuthoringDefinition(raw);
        compiled.push(compileSkillAuthoringDefinition(authored, path.relative(engineRoot, absPath).replace(/\\/g, '/')));
    }

    const generatedAt = new Date().toISOString();
    const metadata = buildSkillLibraryMetadata(compiled, generatedAt);

    await fs.mkdir(generatedDir, { recursive: true });
    await fs.mkdir(metadataDir, { recursive: true });
    await fs.writeFile(generatedFile, renderGeneratedFile(compiled, metadata), 'utf8');
    await fs.writeFile(metadataFile, `${JSON.stringify(metadata, null, 2)}\n`, 'utf8');

    console.log(`Generated ${path.relative(engineRoot, generatedFile)} with ${compiled.length} runtime skills.`);
    console.log(`Generated ${path.relative(repoRoot, metadataFile)}.`);
};

main().catch(error => {
    console.error(error);
    process.exitCode = 1;
});
