import React from 'react';
import type { BiomeBackdropLayerProps } from './biome-backdrop-types';
import { BiomeBackdropDefs } from './biome-backdrop-defs';
import { BiomeBackdropSurfaces } from './biome-backdrop-surfaces';

export const BiomeBackdropLayer: React.FC<BiomeBackdropLayerProps> = ({
    cells,
    biomeClipId,
    biomeClipPoints,
    maskHexPoints,
    biomeFrame,
    biomeCoverFrame,
    undercurrentHref,
    undercurrentMode,
    undercurrentPatternId,
    undercurrentScalePx,
    undercurrentOffset,
    undercurrentScroll,
    undercurrentOpacity,
    crustHref,
    crustMode,
    crustPatternId,
    crustScalePx,
    crustPatternShift,
    crustOpacity,
    crustDetailAHref,
    crustDetailAMode,
    crustDetailAPatternId,
    crustDetailAScalePx,
    crustDetailAShift,
    crustDetailAScroll,
    crustDetailAOpacity,
    crustDetailBHref,
    crustDetailBMode,
    crustDetailBPatternId,
    crustDetailBScalePx,
    crustDetailBShift,
    crustDetailBScroll,
    crustDetailBOpacity,
    crustMaskEnabled,
    crustMaskId,
    crustMaskHoles,
    crustTintActive,
    crustTintColor,
    crustTintOpacity,
    crustTintBlendMode,
}) => {
    return (
        <>
            <BiomeBackdropDefs
                cells={cells}
                biomeClipId={biomeClipId}
                biomeClipPoints={biomeClipPoints}
                maskHexPoints={maskHexPoints}
                biomeCoverFrame={biomeCoverFrame}
                undercurrentHref={undercurrentHref}
                undercurrentMode={undercurrentMode}
                undercurrentPatternId={undercurrentPatternId}
                undercurrentScalePx={undercurrentScalePx}
                undercurrentOffset={undercurrentOffset}
                undercurrentScroll={undercurrentScroll}
                crustHref={crustHref}
                crustMode={crustMode}
                crustPatternId={crustPatternId}
                crustScalePx={crustScalePx}
                crustPatternShift={crustPatternShift}
                crustDetailAHref={crustDetailAHref}
                crustDetailAMode={crustDetailAMode}
                crustDetailAPatternId={crustDetailAPatternId}
                crustDetailAScalePx={crustDetailAScalePx}
                crustDetailAShift={crustDetailAShift}
                crustDetailAScroll={crustDetailAScroll}
                crustDetailBHref={crustDetailBHref}
                crustDetailBMode={crustDetailBMode}
                crustDetailBPatternId={crustDetailBPatternId}
                crustDetailBScalePx={crustDetailBScalePx}
                crustDetailBShift={crustDetailBShift}
                crustDetailBScroll={crustDetailBScroll}
                crustMaskEnabled={crustMaskEnabled}
                crustMaskId={crustMaskId}
                crustMaskHoles={crustMaskHoles}
            />
            <BiomeBackdropSurfaces
                biomeClipId={biomeClipId}
                biomeFrame={biomeFrame}
                biomeCoverFrame={biomeCoverFrame}
                undercurrentHref={undercurrentHref}
                undercurrentMode={undercurrentMode}
                undercurrentPatternId={undercurrentPatternId}
                undercurrentOffset={undercurrentOffset}
                undercurrentOpacity={undercurrentOpacity}
                crustHref={crustHref}
                crustMode={crustMode}
                crustPatternId={crustPatternId}
                crustPatternShift={crustPatternShift}
                crustOpacity={crustOpacity}
                crustDetailAHref={crustDetailAHref}
                crustDetailAMode={crustDetailAMode}
                crustDetailAPatternId={crustDetailAPatternId}
                crustDetailAShift={crustDetailAShift}
                crustDetailAOpacity={crustDetailAOpacity}
                crustDetailBHref={crustDetailBHref}
                crustDetailBMode={crustDetailBMode}
                crustDetailBPatternId={crustDetailBPatternId}
                crustDetailBShift={crustDetailBShift}
                crustDetailBOpacity={crustDetailBOpacity}
                crustMaskId={crustMaskId}
                crustTintActive={crustTintActive}
                crustTintColor={crustTintColor}
                crustTintOpacity={crustTintOpacity}
                crustTintBlendMode={crustTintBlendMode}
            />
        </>
    );
};
